### ISSUE TITLE
Messes with Windows 10 Lock screens and slide shows.

### ISSUE THREAD

**Issue by ZongMan** [ChrisTitusTech/win10script#100]
Tittle says it. All attempts to fix issue never work, please advise. Do you have a script that reverses the essential twerks?

**Comment by ChrisTitusTech** [comment]
This was a very old version of the script, but I am making an undo all option in an update that will include this line... Run it in Powershell to restore lockscreen
Remove-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\Personalization" -Name "NoLockScreen" -ErrorAction SilentlyContinue

**Comment by kAMENkitA** [comment]
Hi Chris.
I really like your Script and I am using it, but I also like Win10 Lock Screen Image Changer.
How would I return the LockScreen functionality after applying Your Script ??

Kind regards.
