### ISSUE TITLE
Remove UAC no prompt from 'low security'

### ISSUE THREAD

**Issue by ShrirajHegde** [ChrisTitusTech/win10script#101]
Please Remove UAC no prompt from 'low security' preset. If people are really desperate let them look up and disable it manually.
Hitting enter on UAC prompt isn't that inconvinient.

No prompt admin access is **No security**, not low security.
This is not recommended even in a VM in my opinion.

**Comment by ChrisTitusTech** [comment]
Agreed, I am removing the security section in the next commit.
