### ISSUE TITLE
POLL: Switch from Chocolatey to WinGet

### ISSUE THREAD

**Issue by DestroyerXyz** [ChrisTitusTech/win10script#111]
I would like feedback from the users of the script if they would like the script to switch from installing apps through Chocolatey to installing them using WinGet (the new Windows Command-Line Package Manager) as it has unattended installs (mostly) and also comes preinstalled with the App Installer package after Windows 10, version 1809.
It is less clunky than chocolatey as it scans the installed packages and knows if the package was uninstalled through Windows Settings whereas Chocolatey just reinstalls the package the next time you update with it.
WinGet is in an early stage of development though
I will make the necessary changes if enough people want it
Like this issue to upvote
Dislike to downvote

**Comment by Brandonbr1** [comment]
i don't have it installed rn

**Comment by ChrisTitusTech** [comment]
Looks like this passes, new update will swap to Winget

**Comment by DestroyerXyz** [comment]
I actually completely forgot about this for a month😜
