### ISSUE TITLE
Optional in diagnostic

### ISSUE THREAD

**Issue by CharanShreehari** [ChrisTitusTech/win10script#117]
I gave my laptop to my brother for his online classes, now he want to install windows 11 in that machine which I previously debloated with this script, now optional diagnostics option is blocked without which he can not download preview build... 
Any option to turn that on?

**Comment by ChrisTitusTech** [comment]
New Script being released this week with that fix to Undo all Telemetry

**Comment by itstusharparmar** [comment]
diagnostic shows 'managed by organizer' even after undoing all tweaks!

**Comment by ChrisTitusTech** [comment]
Type this into command prompt (launch powershell with admin then type cmd) 
RD /S /Q "%WinDir%\System32\GroupPolicyUsers" && RD /S /Q "%WinDir%\System32\GroupPolicy"

**Comment by PeterKW** [comment]
@ChrisTitusTech I tried the command but am still getting managed by organizer: 
![image](https://user-images.githubusercontent.com/13779157/127433092-3f072c74-59b3-4e49-b95b-24f4043f6d4f.png)

Which of the lines would I need to comment out in the program to stop it disabling just diagnostics? 

`#Disable-ScheduledTask -TaskName "Microsoft\Windows\DiskDiagnostic\Microsoft-Windows-DiskDiagnosticDataCollector" | Out-Null

<#Write-Host "Disabling Feedback..."
        If (!(Test-Path "HKCU:\SOFTWARE\Microsoft\Siuf\Rules")) {
            New-Item -Path "HKCU:\SOFTWARE\Microsoft\Siuf\Rules" -Force | Out-Null
        }
        Set-ItemProperty -Path "HKCU:\SOFTWARE\Microsoft\Siuf\Rules" -Name "NumberOfSIUFInPeriod" -Type DWord -Value 0
        Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\DataCollection" -Name "DoNotShowFeedbackNotifications" -Type DWord -Value 1
        Disable-ScheduledTask -TaskName "Microsoft\Windows\Feedback\Siuf\DmClient" -ErrorAction SilentlyContinue | Out-Null
        Disable-ScheduledTask -TaskName "Microsoft\Windows\Feedback\Siuf\DmClientOnScenarioDownload" -ErrorAction SilentlyContinue | Out-Null#>
        

        <#Write-Host "Stopping and disabling Diagnostics Tracking Service..."
        Stop-Service "DiagTrack" -WarningAction SilentlyContinue
        Set-Service "DiagTrack" -StartupType Disabled#>

  <#Write-Host "Stopping and disabling Diagnostics Tracking Service..."
        Stop-Service "DiagTrack"
        Set-Service "DiagTrack" -StartupType Disabled#>

`

**Comment by PeterKW** [comment]
https://appuals.com/cant-change-diagnostic-data-to-full-in-windows-10/ 

When I use these, it goes back to normal but not yet with the reset script

reg delete "HKCU\Software\Microsoft\Windows\CurrentVersion\Policies" /f

reg delete "HKCU\Software\Microsoft\WindowsSelfHost" /f

reg delete "HKCU\Software\Policies" /f

reg delete "HKLM\Software\Microsoft\Policies" /f

reg delete "HKLM\Software\Microsoft\Windows\CurrentVersion\Policies" /f

reg delete "HKLM\Software\Microsoft\Windows\CurrentVersion\WindowsStore\WindowsUpdate" /f

reg delete "HKLM\Software\Microsoft\WindowsSelfHost" /f

reg delete "HKLM\Software\Policies" /f

reg delete "HKLM\Software\WOW6432Node\Microsoft\Policies" /f

reg delete "HKLM\Software\WOW6432Node\Microsoft\Windows\CurrentVersion\Policies" /f

reg delete "HKLM\Software\WOW6432Node\Microsoft\Windows\CurrentVersion\WindowsStore\WindowsUpdate" /f

**Comment by PeterKW** [comment]
> https://appuals.com/cant-change-diagnostic-data-to-full-in-windows-10/
> 
> When I use these, it goes back to normal but not yet with the reset script
> 
> reg delete "HKCU\Software\Microsoft\Windows\CurrentVersion\Policies" /f
> 
> reg delete "HKCU\Software\Microsoft\WindowsSelfHost" /f
> 
> reg delete "HKCU\Software\Policies" /f
> 
> reg delete "HKLM\Software\Microsoft\Policies" /f
> 
> reg delete "HKLM\Software\Microsoft\Windows\CurrentVersion\Policies" /f
> 
> reg delete "HKLM\Software\Microsoft\Windows\CurrentVersion\WindowsStore\WindowsUpdate" /f
> 
> reg delete "HKLM\Software\Microsoft\WindowsSelfHost" /f
> 
> reg delete "HKLM\Software\Policies" /f
> 
> reg delete "HKLM\Software\WOW6432Node\Microsoft\Policies" /f
> 
> reg delete "HKLM\Software\WOW6432Node\Microsoft\Windows\CurrentVersion\Policies" /f
> 
> reg delete "HKLM\Software\WOW6432Node\Microsoft\Windows\CurrentVersion\WindowsStore\WindowsUpdate" /f
