### ISSUE TITLE
stuck at "Updating Powershell Help cmds - I recommend doing a full Update-Help if missing commands"

### ISSUE THREAD

**Issue by hasofn** [ChrisTitusTech/win10script#121]
i run the script as an admin but i am stuck at this

**Comment by Pebrd** [comment]
It worked for me, thanks :)

**Comment by andrewpayne68** [comment]
Worked for me too - thanks!

**Comment by JagMod** [comment]
Same happened to me.
I had to run: **Update-Help -Verbose -Force -ErrorAction SilentlyContinue**
running **Update-Help** by itself didn't resolve it.

**Comment by mrchillington** [comment]
> 
> 
> Same happened to me.
> I had to run: **Update-Help -Verbose -Force -ErrorAction SilentlyContinue**
> running **Update-Help** by itself didn't resolve it.

Had the same issue and this one fixed it.

**Comment by alkingshefo** [comment]
> Same happened to me.
> I had to run: **Update-Help -Verbose -Force -ErrorAction SilentlyContinue**
> running **Update-Help** by itself didn't resolve it.

Worked for me <3

**Comment by Pebrd** [comment]
> Same happened to me.
> I had to run: **Update-Help -Verbose -Force -ErrorAction SilentlyContinue**
> running **Update-Help** by itself didn't resolve it.

Run the script anyways, i dropped error to me after "Update-Help" but i tried the script and worked :)

**Comment by JesFEREM** [comment]
> Same happened to me.
> I had to run: **Update-Help -Verbose -Force -ErrorAction SilentlyContinue**
> running **Update-Help** by itself didn't resolve it.

I was able to get it running by first running windows update and then running update-help, though either could work.

**Comment by eXsoR65** [comment]
Same here, I worked after running `update-help` but i got the below error. I think this is why it got stuck. 
![image](https://user-images.githubusercontent.com/19521349/124652935-b5a01900-de6a-11eb-9dc1-d114ab7f8cfb.png)

Some details to help find the issue @ChrisTitusTech 
Fresh install of Windows 10 21H1
PowerShell Version: 5.1.19041.1023

**Comment by Pebrd** [comment]
> Same here, I worked after running `update-help` but i got the below error. I think this is why it got stuck. 
> 
> ![image](https://user-images.githubusercontent.com/19521349/124652935-b5a01900-de6a-11eb-9dc1-d114ab7f8cfb.png)
> 
> Edit: 
> 
> Seems to be an know issue: https://github.com/MicrosoftDocs/windows-powershell-docs/issues/139
> 
> @ChrisTitusTech you can fix this by passing it the  `-ErrorAction SilentlyContinue` on line [https://github.com/ChrisTitusTech/win10script/blob/master/win10debloat.ps1#L543](https://github.com/ChrisTitusTech/win10script/blob/master/win10debloat.ps1#L543) (don't know enough to update the repro it self sorry 😀) 
> 

the same appeared to me, but if u run the script it should work (at least it worked for me)

**Comment by Sesmicwastaken** [comment]
> > Same here, I worked after running `update-help` but i got the below error. I think this is why it got stuck. 
> > 
> > ![image](https://user-images.githubusercontent.com/19521349/124652935-b5a01900-de6a-11eb-9dc1-d114ab7f8cfb.png)
> > 
> > Edit: 
> > 
> > Seems to be an know issue: https://github.com/MicrosoftDocs/windows-powershell-docs/issues/139
> > 
> > @ChrisTitusTech you can fix this by passing it the  `-ErrorAction SilentlyContinue` on line [https://github.com/ChrisTitusTech/win10script/blob/master/win10debloat.ps1#L543](https://github.com/ChrisTitusTech/win10script/blob/master/win10debloat.ps1#L543) (don't know enough to update the repro it self sorry 😀) 
> > 
> 
> the same appeared to me, but if u run the script it should work (at least it worked for me) 

Yep

**Comment by ChrisTitusTech** [comment]
Thanks made this change! Should no longer get stuck at this part.
