### ISSUE TITLE
Windows Toolbox Essential tweaks not working 

### ISSUE THREAD

**Issue by Mac1962** [ChrisTitusTech/win10script#124]
Having problems with the windows toolbox essential tweaks is no working it creates a restore point but when you click on disable cortana search or any of the other tweaks it’s stuck on essential tweaks you have to keep closing it down and reopening the windows toolbox but essential tweaks is not working I’m on windows 10  ##21h1.

**Comment by NevGi-cpu** [comment]
[#121](https://github.com/ChrisTitusTech/win10script/issues/121) it is a know issue

**Comment by eXsoR65** [comment]
@NevGi-cpu I was just fixed

**Comment by Mac1962** [comment]
I fixed it,do you know why it's doing this,the other windows toolbox wasn't doing this.

**Comment by eXsoR65** [comment]
@NevGi-cpu It's a new requirement. If you read the note when you run Essential tweaks￼. All it's doing is updating the PowerShell help files and cmdlets. If you read the issue #121 I pointed out there a Microsoft know issue with updating PowerShell this way.

**Comment by Mac1962** [comment]
I've just tried windows toolbox the essential tweaks is working but the apps are not installing I've clicked on windows terminal google chrome vlc 7 zip and notepad++ nothing in the start and I'm windows 10 pro 21h1 OS Build 19043.1110

**Comment by eXsoR65** [comment]
> I've just tried windows toolbox the essential tweaks is working but the apps are not installing I've clicked on windows terminal google chrome vlc 7 zip and notepad++ nothing in the start and I'm windows 10 pro 21h1 OS Build 19043.1110

At this point not the same issue man. It best you open a new issue and close this one.
