### ISSUE TITLE
Dont work on my PC 

### ISSUE THREAD

**Issue by pakkumandale** [ChrisTitusTech/win10script#125]
on my pc not work, the aplication freez, i resenly install 21h1 on my asus h310E-R2 i3 8300 nvidea gtx680 16 Gb ram. i from Cuba an my internet acces is to slow. I dont now if dad is the razon. 
note. my inglish is to poor sorry

**Comment by thetaprotocol** [comment]
> on my pc not work, the aplication freez, i resenly install 21h1 on my asus h310E-R2 i3 8300 nvidea gtx680 16 Gb ram. i from Cuba an my internet acces is to slow. I dont now if dad is the razon.
> note. my inglish is to poor sorry

I recommend finding an online translator, writing it out in your native language and pasting in the english, at the very least it might be easier for you.

We would be happy to help but please either reply or edit the initial issue and explain the exact steps you took for it to freeze. Please be aware that several step, especially the Essential tweaks button has many commands being executed and the form GUI will freeze up while the PowerShell window is doing its magic even on an NVME ssd and even longer for a HDD.

**Comment by ChrisTitusTech** [comment]
Try again 21H1 should work now.
