### ISSUE TITLE
How can i remove winget that was installed due to this script?

### ISSUE THREAD

**Issue by wwsmiff** [ChrisTitusTech/win10script#126]

**Comment by thetaprotocol** [comment]
This works for the current implementation of the winget install method, at some point winget will be included in Windows by default, but this will work. I'll write this in a way you can follow even if the download link changes in a later version of the script, assuming the winget install check is not moved to a separate script or the winget package does not see a name change.


1. go [here](https://github.com/ChrisTitusTech/win10script/blob/master/win10debloat.ps1) and search the page for `winget-cli`, find the $download variable url, should look something like this: `$download = "https://github.com/microsoft/winget-cli/releases/download/v1.0.11692/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle"`
3. Copy the random text after 'Microsoft.DesktopAppInstaller_' in this case '8wekyb3d8bbwe', this is the publisher ID you'll use in the next step.
4. Open a admin powershell and paste or type in `Remove-AppxPackage -Package "$(Get-AppxPackage -Name "Microsoft.DesktopAppInstaller" | Select-String -Pattern "Publisher ID"`, replace Publisher ID with the text from the previous step and execute the command. Boom winget is gone from your Path. The installer is also located in the root of the C: drive so you go delete it if you want.

**Comment by wwsmiff** [comment]
Thanks a lot, this worked. I'll close this issue
