### ISSUE TITLE
Updating Powershell Help cmds Never completes.

### ISSUE THREAD

**Issue by CilekciGs** [ChrisTitusTech/win10script#130]
I have tested it on 2 laptops
Laptop 1 Omen 15" dc1002nt nVidia RTX 2070-Q i7-8750H Windows 11
Laptop 2 HP ay000nt Celeron N3060 Windows 11

And both of them got stuck on Updating Powershell Help cmds.

I ran the script before you updated it.

![issue](https://user-images.githubusercontent.com/75041882/124761244-1ee26380-df21-11eb-9fe4-1821e2a20b97.png)

**Comment by eXsoR65** [comment]
@CilekciGs This was just fixed on issue [#121](https://github.com/ChrisTitusTech/win10script/issues/121)
