### ISSUE TITLE
Suggestion: Adding uninstallation of Microsoft Edge, Skype, etc. in the script

### ISSUE THREAD

**Issue by WitherCubes** [ChrisTitusTech/win10script#141]
It is possible to uninstall Microsoft Edge, Skype, Microsoft Feedback and more using winget. So would you please add the option to remove those bloatwares. BTW uninstalling Microsoft Edge using this process may break online links present in Windows Settings app.

**Comment by ChrisTitusTech** [comment]
I agree! Working on this now.
