### ISSUE TITLE
 Forza Horizon 4 wont pass SplashScreen after applying Script

### ISSUE THREAD

**Issue by kAMENkitA** [ChrisTitusTech/win10script#152]
HI Chris. I am using Your script for the first time. But something unexpected has happened. Me and my family members play a lot Forza Horizon 4. After applying your script, my Forza Horizon could not pass initial screen and  crashed after cca. 2 mins. I was disappointed, I've thought you messed something with Windows Store apps relating Xbox. Inspecting Event Viewer Ive got on my mind to check Time. And guess what, that was the problem. Your script somehow changes Time Zone and I was +2hours from my actual time zone (Croatia). After I've changed time settings and synchronise it - my Forza Horizon4 started properly !!
Could you fix issue with Time zone setting? Anyway, You've made great script, I will follow your work :)
Kind regards.

**Comment by PScoriae** [comment]
Can confirm. The time zone change occurs and after trying to revert it to my local time zone, it reverts back on reboot.

**Comment by PScoriae** [comment]
Found a fix. I dug into the script's code and searched for UTC. You need to delete the registry entry named RealTimeIsUniversal in HKLM:\SYSTEM\CurrentControlSet\Control\TimeZoneInformation

**Comment by kAMENkitA** [comment]
Thank You  @PScoriae for research !
Thank You Chris, too

**Comment by Carterpersall** [comment]
@kAMENkitA if this issue is resolved, please close this issue to prevent clutter in the issues tab.
