### ISSUE TITLE
Issue w/ 21H2 - Winget doesn't install

### ISSUE THREAD

**Issue by Duderinio** [ChrisTitusTech/win10script#157]
On win10 21H2 the programs aren't installing at all after the press of the buttons. Also winget is installing after every lunch of the script  ... Any guess ?

**Comment by FlexMcMurphy** [comment]
I have the same problem on Win 10 Pro 21H1, OS Build: 19043.1110

**Comment by ChrisTitusTech** [comment]
Try now, working on a new winget install process.

**Comment by FlexMcMurphy** [comment]
Working for me now. Thank you Chris. No more OneDrive and other Windows junk. BOOM!

**Comment by VoladorBoy** [comment]
I have the same issue 
"winget is not found, installing it right now
Downloading latest winget release"
pls help me, I love this tool

**Comment by TrisBits** [comment]
@VoladorBoy  is your winget install problem similar to this other reported issue https://github.com/ChrisTitusTech/win10script/issues/164

**Comment by ChrisTitusTech** [comment]
This has been fixed and winget now installs using the MS Store.
