### ISSUE TITLE
Issue w/ 21H1 (19043.1151)

### ISSUE THREAD

**Issue by NAlexQ** [ChrisTitusTech/win10script#164]
On win10 21H1 the programs aren't installing at all after the press of the buttons. Also winget is installing after every lunch of the script.
![Captură](https://user-images.githubusercontent.com/88576598/128594181-173d0e1f-d961-42f0-bc3d-3f0e9c4415aa.JPG)

**Comment by ReaamMarjana** [comment]
same thing here

**Comment by CarlSpacklersGopher** [comment]
More info: This is because Winget install is failing due to a missing dependency.  When running each line individually, I get this error.
![image](https://user-images.githubusercontent.com/43297884/128634667-44505943-b99f-4c3c-92eb-00463c40a228.png)

The error says that there is a Microsoft.VCLibs.140.00.UWPDesktop framework installed, but looks like it's not the correct version.  Needs to be at least 14.0.29321.0 and currently installed for me is 14.0.27629.0

**Comment by CarlSpacklersGopher** [comment]
Workaround:  Go to the [Winget Github page](https://github.com/microsoft/winget-cli), where there is this quote under the Installing the Client / Manually Update section:

> You may need to install the [VC++ v14 Desktop Framework Package](https://docs.microsoft.com/troubleshoot/cpp/c-runtime-packages-desktop-bridge#how-to-install-and-update-desktop-framework-packages). This should only be necessary on older builds of Windows 10 and only if you get an error about missing framework packages.

Click that link it will pop a page to choose a link for an installer for V14.0.29321.0 .  You're looking for the Microsoft.VCLibs.x64.14.00.Desktop.appx link.  Run the downloaded installer and confirm that the version is 14.0.29321.0
![image](https://user-images.githubusercontent.com/43297884/128635602-7efc80c8-9749-487e-a743-c1d8be2d7eec.png)

I installed that and re-ran the script.  Everything worked for me from there on out. 

I don't know how to download the newest package via powershell, so I can't contribute to the script, but that's what fixed it for me.

**Comment by bleugray** [comment]
The above fixed the issue for me as well.  thanks @CarlSpacklersGopher

**Comment by NAlexQ** [comment]
So, no fix for the main problem?

**Comment by hakova** [comment]
Above solution does not work anymore since there is a newer version of this package (Microsoft Visual C++ 2015 UWP Desktop Runtime Package is already installed. The installation of V14.0.29321.0 fails due to that and recommends uninstalling the newer package first, which I couldn't find a way how.

**Comment by TrisBits** [comment]
This is an issue with winget.  The apxbundle does not install the VCLibs dependency, if it is not present on your version of Windows.

https://github.com/microsoft/winget-cli/issues/401

**Comment by hakova** [comment]
> This is an issue with winget. ...

Thank you for clarifying this. I did install some of those apps that I wanted manually to be honest, it is not a big issue. As long as the "Essential Tweaks" part of the script works, which it does I believe, the rest is a little extra anyway.

**Comment by ChrisTitusTech** [comment]
This has been fixed as I changed the way winget installs.
