### ISSUE TITLE
Does the Individual Script Auto Runs from Essential Tweaks?

### ISSUE THREAD

**Issue by NevGi-cpu** [ChrisTitusTech/win10script#167]
I see that there are 2 Individual Script. Do they auto run when we do Essential Tweaks from Debloat Box?

**Comment by mrhaydendp** [comment]
No but certain parts in the individual scripts are implemented into essential tweaks.

**Comment by Carterpersall** [comment]
@NevGi-cpu if this issue is resolved, please close this issue to reduce clutter in the issues tab.
