### ISSUE TITLE
Snip & Sketch

### ISSUE THREAD

**Issue by rKrishna97** [ChrisTitusTech/win10script#168]
After running this script the performance is great. But when I do winkey +shift + s and take screenshot using snip & sketch. I'm not getting the notification. This is a windows feature I use a lot. So I always have to open the app and then take the screenshot. But it won't work when I use shortcut

**Comment by pratyakshm** [comment]
Try re-installing the Snip & Sketch app.

**Comment by rKrishna97** [comment]
> Try re-installing the Snip & Sketch app.

I tried that. It didn't work after reinstalling
