### ISSUE TITLE
Unable to Install OneNote

### ISSUE THREAD

**Issue by rKrishna97** [ChrisTitusTech/win10script#169]
After running this I'm unable to install OneNote. I have share the error I'm getting in the screenshot
![Screenshot 2021-08-16 224816](https://user-images.githubusercontent.com/45824954/129603631-87d60525-2d36-45af-b90c-ae87d0b7d4d9.png)

**Comment by pratyakshm** [comment]
Try running Windows Update troubleshooter.

**Comment by rKrishna97** [comment]
> Try running Windows Update troubleshooter.

Tried that. Still unable to install OneNote

**Comment by ChrisTitusTech** [comment]
This can be a couple things, make sure that background apps is enabled and you did NOT use the debloat of Windows store.
