### ISSUE TITLE
Applying Essential Tweaks disables Background Apps

### ISSUE THREAD

**Issue by kAMENkitA** [ChrisTitusTech/win10script#170]
HI Chris,
I did not know that applying Essential Tweaks disables B A's. I am aware that you put button for disabling B A who wants to do it.
I realised the issue when my MS Games started to crash or getting disconnected - I checked the BackGroundApps under Settings & saw they all are disabled.
Could you improve your script by removing that line with disabling B A under Essential tweaks?

Regards!

**Comment by ChrisTitusTech** [comment]
Thanks for pointing this out. I think it was a bad pull request that put this in. I'll revert this to not touch background apps!

**Comment by kAMENkitA** [comment]
Thank You Chris.
All the best.

**Comment by damian101** [comment]
Another issue is caused by this: #253

**Comment by Carterpersall** [comment]
@kAMENkitA if this issue is resolved, please close this issue to reduce clutter in the issues tab.
