### ISSUE TITLE
Windows Search not finding apps after running essential tweaks

### ISSUE THREAD

**Issue by bam932** [ChrisTitusTech/win10script#171]
Hi Chris!
I ran your debloat script and then proceeded with the essential tweaks. I restarted my computer and my newly installed applications are not being picked up by Windows Search. After realizing that, i enabled Cortana / Search because you said in the video that Cortana and Search are linked together.  I restarted my computer then it still doesnt work for some reason. Any guess or fix?

**Comment by CiHel** [comment]
go to service find windows search enable it

**Comment by vroktylF** [comment]
Same problem here, new apps not showing up in start menu search even if they are in the start menu. Sometimes when removing apps from start menu they still show up in search but not possible to interacted with. Cant find the cause of it. Windows search service is enabled.

**Comment by bmac6996** [comment]
I will add that i had the same issue after newly install 21h2 and running the debloat script.  I tried troubleshooting what I can.  Tried some Windows search settings and allowing it to index my programdata folder and my username\profile folder but still doesn't show my apps.  

Going to wipe and reinstall and not "disable search" and kinda go from there.. hopefully that works without search being breaking.

**Comment by bmac6996** [comment]
**just an update.  After two reinstall of Windows 21H2 , I feel confident that something in the "essential tweaks" script is breaking the search and indexing of apps function.  I ran other parts of the toolbox and they work and when I skipped the essential tweaks part, app still remain as part of the search.

**Comment by Carterpersall** [comment]
Your solution is likely in #253

**Comment by bam932** [comment]
> Your solution is likely in #253

Thanks!
