### ISSUE TITLE
[Feature Request] "Suggest ways I can finish settting up my device.."

### ISSUE THREAD

**Issue by MuseHorizon** [ChrisTitusTech/win10script#172]
Hi,

It would be nice if this script could turn off "Suggest ways I can finish setting up my device to get the most out of Windows". This pop-up is very annoying.

![suggest_ways](https://user-images.githubusercontent.com/41480138/130710352-58b19a7f-10ad-4fea-b703-e8652737a6fa.png)

Thanks for the work on this script - I run it on all my Windows installs.

**Comment by TrisBits** [comment]
Found the following on reddit and verified it is indeed the correct registry key.


HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\UserProfileEngagement

Key = ScoobeSystemSettingEnabled (DWORD type) and set to 0 to disable the notification

*Note - if you never touched this setting, the "UserProfileEngagement" folder and the key to toggle will not exist yet. You can create them anyway or toggle things off in Settings and watch the folder and key get set in the registry.
*Note - You have to be on W10 2004+ (build 18945 and later) for this to be available.

**Comment by mrhaydendp** [comment]
I made a script and a `.reg` file that [disables the feature](https://github.com/mrhaydendp/RemoveEdge/tree/main/Individual%20Scripts). They both do the same task just personal preference.

**Comment by MuseHorizon** [comment]
@mrhaydendp looks good! I will use your script going forward.
