### ISSUE TITLE
winget is not installing, so, no program can be installed.

### ISSUE THREAD

**Issue by Cuauhtli-dev** [ChrisTitusTech/win10script#177]

**Comment by mrhaydendp** [comment]
Run this command to open a MS Store window that directly installs winget.
```
Start-Process "ms-appinstaller:?source=https://aka.ms/getwinget"
```

**Comment by madnj** [comment]
This appears to be related to new Winget installs installing to a location that is not in the "Path" variable.  See the below link for details/fix:

https://github.com/microsoft/winget-cli/issues/210

Follow the directions to add %userprofile%\AppData\Local\Microsoft\WindowsApps to Path and the script runs/works fine.  Not sure what's going on with the Winget install, but that's what's broken.

**Comment by ChrisTitusTech** [comment]
Yup the temp file directory looks to be messed up in the latest winget install. You can also change your temp directory in system settings to fix this by modifying the system variable. 
I changed my temp folder to be C:\Temp
