### ISSUE TITLE
Winget already installed but not detected, force install.

### ISSUE THREAD

**Issue by herkow** [ChrisTitusTech/win10script#181]
Clean, fresh Win10Pro install. All updates done. Update-Help done. WinGet updated to last version from STORE. Script says winget is not installed. You should put an option to bypass this in case we don't need to install any programs, just debloat, becasue it breaks a CLEAN INSTALL.

**Comment by madnj** [comment]
Already posted about this - fix your PATH variable and it works fine:

https://github.com/ChrisTitusTech/win10script/issues/177#issuecomment-910484823

**Comment by herkow** [comment]
That doesn't work. Still keeps asking to install. Funny thing is I allowed the script to install winget, and the next time I run it, it says that winget is not found. I guess someone forgot to keep it simple...
