### ISSUE TITLE
Lower Frames on a game after using 

### ISSUE THREAD

**Issue by pohihihisocks** [ChrisTitusTech/win10script#182]
Somehow this Debloater reduced the average frames I get in a game(Roblox), I used to be getting 130+ but now its 90< What could have caused it? The only visible thing it did was give me is a much much more responsive OS, but the bad side is the lower frames, so it's a double sided blade. Even in a game called Osu I used to get 240 fps but now it dropped to a sad number of 170.
Could it have deleted some helpful files that are incorporated with game performance?

**Comment by ChrisTitusTech** [comment]
That doesn't make sense, but as this disables many services. Possibly a reboot and graphics driver update may help. However, there is nothing in the script that could effect performance like this.
