### ISSUE TITLE
Script crashes on AMD Phenom II, ver. 20H1 PC's. 

### ISSUE THREAD

**Issue by WNG555** [ChrisTitusTech/win10script#183]
Chris,
I ran this script previously (older version?) on a Win 10 vers. 2004 (20H1) AMD Phenom 2 PC and it worked fine.  I just tried this update and it crashes in Powershell on this PC. 
I ran it in hopes to get Winget.  

Just ran the script on another untouched Win10 20H1 AMD Phenom 2 PC and got the same error.  Powershell simply closes down. 

Can't read any error messages.
What is the issue?

Is there some way for me to debug on my end?  Thanks for your consideration!

**Comment by ChrisTitusTech** [comment]
Probably the winget install. I just changed the method it deploys, try again now.

**Comment by WNG555** [comment]
Thanks Chris! I'll give it a go this weekend! 
-- 
Best Regards, 
William Ng 
***@***.*** 
"You only grow old when your dreams are replaced by regrets." 

    On Thursday, September 23, 2021, 09:47:21 AM MST, Chris Titus ***@***.***> wrote:  
 
 


Probably the winget install. I just changed the method it deploys, try again now.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
