### ISSUE TITLE
The window is too big, can not see the whole window

### ISSUE THREAD

**Issue by minhntp** [ChrisTitusTech/win10script#192]
Hi.

I'm using a 1920x1080 screen, with 125% scaling.
The GUI window is too big for the screen and I can't see many options at the bottom.

![Screenshot (5)](https://user-images.githubusercontent.com/10728524/134915723-719afb9b-c92c-4d2e-bf0a-bfd435df357e.png)

**Comment by sunnetmedia** [comment]
Pls Update this GUI Screen Size Fix 
Smaller Size Laptops screens cant reach  
Your most valuable Options Hidden below "App removal" 

Thanks for your tool and update

**Comment by adamz01h** [comment]
Fixed in https://github.com/ChrisTitusTech/win10script/pull/193

**Comment by ChrisTitusTech** [comment]
Thank you Adamz! for the addition. I'm working on a DPI solution that might be a bit more elegant in the future, but a great fix for now.

**Comment by minhntp** [comment]
The scolling works well when the window is maximized. If the windows is not maximized, there is a little portion covered by the taskbar. I think you should put some bottom margin to the bottom component.
