### ISSUE TITLE
Downloader-XP TRJ - Avast Detected on download

### ISSUE THREAD

**Issue by CallworksWest** [ChrisTitusTech/win10script#20]
Your download string:
 iex ((New-Object System.Net.WebClient).DownloadString('https://git.io/JJ8R4'))  

Shows a Threat warning of the following:
Infected with BV:Downloader-XP [Trj]

Was following Steps on your website: https://christitus.com/debloat-windows-10-2020/

**Comment by higherleveling** [comment]
did he answer at alll???

**Comment by ChrisTitusTech** [comment]
False positive. It is detecting downloads through powershell. Any script will get flagged for this.
