### ISSUE TITLE
VLC Media Player Install

### ISSUE THREAD

**Issue by adamkagdi** [ChrisTitusTech/win10script#201]
When I tried to install VLC Media player, it didn't install that. Instead it showed me 'Installed NotePad++' or something around those lines. When I checked the powershell, it showed that there was name problem and I had to choose between 2 packages. Hope to get it fixed soon.
Thanks

**Comment by ssrahul96** [comment]
refer https://github.com/ChrisTitusTech/win10script/issues/203#issuecomment-933127788

**Comment by ChrisTitusTech** [comment]
This is fixed
