### ISSUE TITLE
Can't resize window

### ISSUE THREAD

**Issue by andercard0** [ChrisTitusTech/win10script#223]
Hello!

I'm trying to run your solution on my laptop but due to my resolution i think can't resize the window to see/choose other options 

![image](https://user-images.githubusercontent.com/43047877/140677560-85acd178-ca3c-491b-af1a-1bdc35e53d88.png)

It would be possible to make the screen sizeable ? 

Thank you!!

**Comment by AaravHattangadi** [comment]
Hey @andercard0 ,
I'm facing the same problem. I was able to remedy it by clicking the maximize button, and making it full screen. You might want to try that.

**Comment by andercard0** [comment]
> Hey @andercard0 , I'm facing the same problem. I was able to remedy it by clicking the maximize button, and making it full screen. You might want to try that.

wow yeah! works good as a workaround thank you

**Comment by DocAElstein** [comment]
I think this other recent issue comment might be of interest
https://github.com/ChrisTitusTech/win10script/issues/196#issuecomment-1041595552

Alan
