### ISSUE TITLE
After using this i get frequent wifi disconnects

### ISSUE THREAD

**Issue by Official-Husko** [ChrisTitusTech/win10script#23]
i tried privatewin10 and i had the same issue until i reverted it back to normal settings. Do you know what might cause this issue? i would like to keep my windows 10 debloated but with the frequent disconnects that's not possible at its very annoying.

**Comment by ChrisTitusTech** [comment]
This could be something with Wi-Fi Sense, but generally, this would solve issues with Wifi not make them worse.
