### ISSUE TITLE
[Issue] Brave Browser Ads don't seem to work after using minimal.ps1

### ISSUE THREAD

**Issue by Zefferis** [ChrisTitusTech/win10script#24]
Hey there, I used the minimal.ps1 powershell script as a way to debloat windows; which also means it's my first time using Brave.

I've enabled Brave Rewards + Ads, but it seems Brave uses OS notifications to show advertisements - of which they're disabled in the minimal.ps1 script.

So perhaps a toggle is needed to change the script if someone wants to use the Brave Browser + Brave Rewards.

On the same note, I would like to use Brave Rewards but am unsure of what needs to be changed script wise to make the feature work.

**Comment by ChrisTitusTech** [comment]
I am moving this to winget and shouldn't see any more issues with it. The minimal powershell will eventually be archived.
