### ISSUE TITLE
Edge browser managed by Oranization

### ISSUE THREAD

**Issue by BlazeHek** [ChrisTitusTech/win10script#243]
After running the script, edge doesnt have autofill in the search bar and it shows "Managed by your Organisation".

**Comment by kasai2210** [comment]
Heyy, I know the fix for this, just open the registry editor and navigate to this location - Computer\HKEY_CURRENT_USER\SOFTWARE\Policies\Microsoft\Edge

Then just change the value of the attribute you want to enable to 1 from 0.
Hope this helps you.
