### ISSUE TITLE
Exception calling "DownloadString" with "1" argument(s): "The remote server returned an error: (503) Server Unavailable."

### ISSUE THREAD

**Issue by kasai2210** [ChrisTitusTech/win10script#252]
This error is showing up while I try to run the script using the elevated power shell. Anyone else who is experiencing the same issue comment on this thread to highlight this issue.

**Comment by DevTushit17** [comment]
Same thing has been happening with me, hopefully it gets fixed soon.

**Comment by Wolfofworld** [comment]
Same here also,
It used to work like a charm earlier.

**Comment by gapi78** [comment]
i have the same problems also

**Comment by 5D-Speed** [comment]
same with me. used to work until i reset my pc

**Comment by 5D-Speed** [comment]
> This error is showing up while I try to run the script using the elevated power shell. Anyone else who is experiencing the same issue comment on this thread to highlight this issue.



> Same thing has been happening with me, hopefully it gets fixed soon.



> Same here also, It used to work like a charm earlier.



> i have the same problems also

hey guys. had the same problem, tried it again now and it worked. hopefully it does for you too

**Comment by Wolfofworld** [comment]
> This error is showing up while I try to run the script using the elevated power shell. Anyone else who is experiencing the same issue comment on this thread to highlight this issue.

The issue had been resolved.

**Comment by kasai2210** [comment]
Yeah the issue is fixed now, so I closing it. Thanks to the Devs😀😀
