### ISSUE TITLE
Steam games not running

### ISSUE THREAD

**Issue by effletini** [ChrisTitusTech/win10script#26]
The steam games icons disappeared and I can't run any of the games. Any ideas how to fix?

**Comment by dennyamarojr** [comment]
> The steam games icons disappeared and I can't run any of the games. Any ideas how to fix?

Go to steam launcher and them select the game in the library and right-click and make a shortcut or double click the icon and you will see to open the icon with internet (don't remember the name) but is global icon select this and them you will fix your icons.

**Comment by NotAnotherTestAccount** [comment]
How to fix the Steam “.url” desktop shortcut glitch

https://medium.com/@jacob.swanson.n/how-to-fix-the-steam-url-desktop-shortcut-glitch-8ed8bdf08939#:~:text=If%20your%20Steam%20desktop%20icons,default%20apps%20by%20file%20type%E2%80%9D.

**Comment by ChrisTitusTech** [comment]
The file association tweaks were removed that caused this.
