### ISSUE TITLE
Add the oprion for waterfox

### ISSUE THREAD

**Issue by bee-Michi** [ChrisTitusTech/win10script#268]
Hi! I'm not sure if i cloud PR it, but it would be good if we cloud add the Waterfox browser https://www.waterfox.net/.
Basically, it's a completely free and open source alternative to Mozilla Firefox, without mozzilas ongoing telemetry and changing position regarding privacy. 
So yeah, adding this as an option would maybe add more possibility. Also one last thing, waterfox is actually faster than Firefox

Ps: Nobody pays me for saying these things!

**Comment by micziz** [comment]
Can this be closed?

**Comment by bee-Michi** [comment]
Ok
