### ISSUE TITLE
Issue with waking up after placing to sleep

### ISSUE THREAD

**Issue by AlBie24** [ChrisTitusTech/win10script#27]
Please fix the issue. I Everytime I place the system to sleep, it will be stuck to the lockscreen

**Comment by bburt91** [comment]
> Please fix the issue. I Everytime I place the system to sleep, it will be stuck to the lockscreen

This sounds like it could be an issue with Hibernation. Open PowerShell or Command Prompt as Administrator and run `powercfg.exe /hibernate on`

**Comment by ChrisTitusTech** [comment]
Yup I don't use hibernate and disable it by default. @bburt91 is correct on the re-enabling procedure.
