### ISSUE TITLE
[FEATURE REQ] Custom O&OShutup script

### ISSUE THREAD

**Issue by ArijitKHaldar** [ChrisTitusTech/win10script#276]
I think some users like me would benefit from adding a clickable button which opens windows explorer to browse and select our pre-made o&oshutup.cfg and run it, bypassing the default one you have already provided.

This provides a granular control over what to add and what to omit from the group policies, rather than enabling or disabling a few later, which just adds another step to the process, plus, your GUI is amazing, and I do feel lazy to setup some things that I personally need again, after using your tool 😛

**Comment by Carterpersall** [comment]
The script in Pull Request #285 will no longer override ooshutup10.cfg in the script root allowing you to add your own custom preset there.

**Comment by ArijitKHaldar** [comment]
Thanks...that's helpful
