### ISSUE TITLE
30th/October/2020 - AVAST intercepted virus BV:Downloader-XP on both minimal.ps1 and win10debloat.ps1

### ISSUE THREAD

**Issue by JimFenner** [ChrisTitusTech/win10script#28]
Hi Chris, 
     Antivirus alarm bells went off when I unzipped your zip file today 30th/October/2020 (Australian time) 
both minimal.ps1 and win10debloat.ps1

Jim Fenner
jim@jimfenner.com

**Comment by higherleveling** [comment]
I just did the same and got an alert too!!

**Comment by ChrisTitusTech** [comment]
Any download from Powershell scripts will generally cause a false positive in Anti Virus programs. All the code is open source and can be reviewed by anyone to see what is being downloaded.
