### ISSUE TITLE
Essential Tweaks will break Edge's Functionality even after restoring

### ISSUE THREAD

**Issue by Venipa** [ChrisTitusTech/win10script#284]
After using the essentials tweak my edge is "debloated" yes but if i want to undo the tweaks it wont undo changes made to edge:
![image](https://user-images.githubusercontent.com/17952364/152703500-0e4944cc-a518-4de1-acb1-9250d824c2b7.png)

Policies active:
![image](https://user-images.githubusercontent.com/17952364/152703523-b1875bb0-c224-4691-a483-abf615ad0630.png)

Im unable to search my own history in the web address bar which renders web dev'ing with edge a pain in the a**.

("SearchSuggestEnabled" is disabled)

**Comment by mimed95** [comment]
I encountered the same problem. This can be fixed by deleting the registry entries for the policies in Edge as described in https://www.askvg.com/fix-your-browser-is-managed-by-your-organization-message-in-microsoft-edge/

**Comment by Venipa** [comment]
> I encountered the same problem. This can be fixed by deleting the registry entries for the policies in Edge as described in https://www.askvg.com/fix-your-browser-is-managed-by-your-organization-message-in-microsoft-edge/

didnt work, just used O&O Shutup 10 and reenabled my required policies
