### ISSUE TITLE
What are the 'Essential Tweaks'?

### ISSUE THREAD

**Issue by ryanpcmcquen** [ChrisTitusTech/win10script#295]
Is there a list of what commands 'Essential Tweaks' runs?

**Comment by Evan-Galvin** [comment]
Absolutely.... You just need to look:
https://github.com/ChrisTitusTech/win10script/blob/master/win10debloat.ps1

Lines 874~~>1163 contains all commands issued by "Essential Tweaks".

In the future you should not create an issue for a project when you are simply trying to get an answer to a question

**Comment by ryanpcmcquen** [comment]
I was more wondering if there was a non code list. I don't mind reading it myself, but I think a lot of users won't grok what certain registry write commands actually do.

What would be a better place for this question? I actually prefer questions in GitHub issues on my own projects, makes for a nice informal wiki when other people are wondering about something.

**Comment by khaneliman** [comment]
> I was more wondering if there was a non code list. I don't mind reading it myself, but I think a lot of users won't grok what certain registry write commands actually do.
> 
> What would be a better place for this question? I actually prefer questions in GitHub issues on my own projects, makes for a nice informal wiki when other people are wondering about something.

Add a label and then close your issue, if your question is answered, then. Developers will want to scan the issues for actual bugs and if people are labeling their issues it's much harder to scan.

**Comment by ryanpcmcquen** [comment]
Label assignment is only available with permission.

**Comment by khaneliman** [comment]
> Label assignment is only available with permission.

Ah yeah.. makes sense. Would be nice to have a issue automation set up to label automatically on title.
