### ISSUE TITLE
Stuck on "Showing task manager details..."

### ISSUE THREAD

**Issue by MohammedMehdiTBER** [ChrisTitusTech/win10script#302]
Stuck on "Showing task manager details..." in 22572.1 build

**Comment by Carterpersall** [comment]
Duplicate of #299 
The issue occurring to two different people like this means that this is likely not an isolated incident and is a real problem. If I get the time I'll look into it in a VM.

**Comment by SimPilotAdamT** [comment]
Should be fixed in #304
