### ISSUE TITLE
I can't stop/disable Windows defender

### ISSUE THREAD

**Issue by 0TTA** [ChrisTitusTech/win10script#311]
So I'm downloading Cyberpunk 2077 to my NAS using GOG GALAXY, and for some reason, it gives me installation failed. One of the solutions was to turn Windows defender off. But with this script applied, I can't.

**Comment by Carterpersall** [comment]
Is the 'Real-time Protection' toggle grayed out? Windows defender (that I know of) is not forced to be enabled by the script.

**Comment by Carterpersall** [comment]
@0TTA got any updates on the issue?

**Comment by 0TTA** [comment]
> @0TTA got any updates on the issue?

Yes, I reinstalled Windows, then installed the game, then I applied the script.

**Comment by Carterpersall** [comment]
Good to hear that the issue was solved! If you have no further issues please close this issue to prevent clutter in the issues tab.
