### ISSUE TITLE
Windows App Store 

### ISSUE THREAD

**Issue by Rentheiedman** [ChrisTitusTech/win10script#33]
Can I get an option where I can bring back to app store.

**Comment by gfelipe099** [comment]
You can use the following command which will reinstall all UWP apps:
`Get-AppxPackage -AllUsers| Foreach {Add-AppxPackage -DisableDevelopmentMode -Register “$($_.InstallLocation)\AppXManifest.xml”}`

**Comment by ShlomiD83** [comment]
you can install windows store from here if you uninstalled it.

https://github.com/kkkgo/LTSC-Add-MicrosoftStore
