### ISSUE TITLE
Remove adobe and use Sumatra

### ISSUE THREAD

**Issue by mhf-ir** [ChrisTitusTech/win10script#34]
More lighter and opensource
https://www.sumatrapdfreader.org/free-pdf-reader.html
https://github.com/sumatrapdfreader/sumatrapdf

**Comment by RamonUnch** [comment]
+1
I am all for Sumatra, it is a very nice pdf viewer. I use it on all of my windows.

**Comment by ChrisTitusTech** [comment]
Never heard of it until now, I'll add it as an option to the GUI in the future. 
Thank you!
