### ISSUE TITLE
Clipboard

### ISSUE THREAD

**Issue by firstimpressionmusic** [ChrisTitusTech/win10script#35]
My clipboard is disabled, is there anyway to enable it?
here is my version
https://github.com/firstimpressionmusic/win10script/edit/master/win10debloat.ps1

**Comment by natri23** [comment]
Yeah, It's the O&OShutup10 that disabled Clipboard History.
You can run the O&OShutup10 and search for Clipboard to re-enable it.

**Comment by natri23** [comment]
Or you can edit the oooshutup10.cfg like the commit above

**Comment by firstimpressionmusic** [comment]
thanks

**Comment by 3371-Alpha** [comment]
You can also fix this in Regedit by going to "Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\System" and turning "allowclipboard" to 1
