### ISSUE TITLE
Windows Defender Icon.

### ISSUE THREAD

**Issue by savanteN** [ChrisTitusTech/win10script#36]
Hey there, I have a issue where the Windows Defender Icon is removed from the taskbar. 

Ive tried the restore script but it didnt put the icon back down in the taskabar, I've checked the settings aswell so it shows all icons, Its just gone ..

Any fix for this or suggestion?

**Comment by dennyamarojr** [comment]
Open regedit and them go to HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Run
Right-click in the blank space New> Expandable string value
Value name: SecurityHealth
Value data: %windir%\system32\SecurityHealthSystray.exe

Restart your computer, after that the icon should be back.

**Comment by savanteN** [comment]
> Open regedit and them go to HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Run
> Right-click in the blank space New> Expandable string value
> Value name: SecurityHealth
> Value data: %windir%\system32\SecurityHealthSystray.exe
> 
> Restart your computer, after that the icon should be back.

Thanks alot! 👍

**Comment by dennyamarojr** [comment]
Your Welcome, maybe Chris should add this to revert script 👍
