### ISSUE TITLE
Feature Request: Enable Your Phone (if possible)

### ISSUE THREAD

**Issue by untraceablez** [ChrisTitusTech/win10script#38]
Hello!

Wanted to start off by saying fantastic script, lets me get every ounce of performance out of my system w/o the bloat, however there is one Windows function I am missing. I actually am a fan of the Your Phone app, being able to reply to texts natively on Windows is actually really nice, and being able to screen share my phone to the PC is also a useful bonus. 

I don't know exactly how complicated it would be to be able to enable the Your Phone app once again, but I'm willing to do what's necessary, it's quite handy for my workflow.

**Comment by Schnauzer-World** [comment]
Did you try just reinstalling it from the MS Store? https://www.microsoft.com/en-us/p/Your-phone/9nmpj99vjbwv?activetab=pivot:overviewtab

**Comment by untraceablez** [comment]
> Did you try just reinstalling it from the MS Store? https://www.microsoft.com/en-us/p/Your-phone/9nmpj99vjbwv?activetab=pivot:overviewtab

I did not, I ended up re-installing later that day since I hadn't gotten to far with Windows setup. I'll try it on a VM soon to verify if that fixes it before I run it on the main system again.

**Comment by andreluizmg** [comment]
Yes this happens to me too, and cant bypass and occurs the following message :
"This application has been blocked by the system administrator
Contact your system administrator to learn more."

Tried both reset options on settings but nothing message still appears

**Comment by ChrisTitusTech** [comment]
Removing Shared Experiences tweaks that cause this to happen. I'll do a fix rollup to the restore scripts, but future runs of the script will no longer cause this to happen.
