### ISSUE TITLE
Limit Reserve Bandwidth

### ISSUE THREAD

**Issue by firstimpressionmusic** [ChrisTitusTech/win10script#4]
Under QoS Packet Scheduler, can anyone add Limit Reserve Bandwidth to 0?

**Comment by Dyrimon** [comment]
@ChrisTitusTech Hi Chris, isn't the Limit Bandwidth tweaks included in the Essential Tweaks? I had to manually do it following your video even after running the Essential Tweaks script from the toolbox. Although I was using the "High" security option. Could *that* be an effect?
