### ISSUE TITLE
Location services and clipboard disabled

### ISSUE THREAD

**Issue by EddoWagt** [ChrisTitusTech/win10script#40]
After running this script I can't use location services anymore, same for the clipboard like another user mentioned. It'd be great if I can re-enable those services as I really want to use those. Does anybody know how?

**Comment by dennyamarojr** [comment]
O&O Shutup 10 disable the location services and clipboard
To restore clipboard history go to regedit and navigate to HKEY_CURRENT_USER\SOFTWARE\Microsoft\Clipboard
and delete the value EnableClipboardHistory or double-click and them put value data from 0 to 1

For location services go to regedit and navigate to HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\location
and double-click in the value and them set the value data from Deny to Allow

Maybe chris should add this to revert script 👍

**Comment by Emil89EC** [comment]
I have changed the registry value to Allow for the location services and I still can't enable it back. Is there something else I'm missing?

**Comment by dennyamarojr** [comment]
XD , I will add this into the revert script. Glad that works for you.

**Comment by EddoWagt** [comment]
Thanks! I ended up resetting windows because the installation was a day old, so whatever. I'm gonna assume this would've worked! :)
