### ISSUE TITLE
[INFO] Windows Defender Icon Missing

### ISSUE THREAD

**Issue by dennyamarojr** [ChrisTitusTech/win10script#41]
Hi chris,

Recently I run the script win10debloat and it seems that you don't add the build for Windows 10 20H2 in securityhigh.addclick

so instead of having this command
Set-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Run" -Name "SecurityHealth" -Type ExpandString -Value "`"%ProgramFiles%\Windows Defender\MSASCuiL.exe`""

We should have this command here
Set-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Run" -Name "SecurityHealth" -Type ExpandString -Value "%windir%\system32\SecurityHealthSystray.exe"

Here's a screenshot
![image](https://user-images.githubusercontent.com/36896116/101054442-cf017f80-3580-11eb-8ef1-99f86a734091.png)

**Comment by dennyamarojr** [comment]
Just another info, for the users are not seeing the Windows Defender icon in the taskbar.  You need go to Settings and them enable WD to show the icon in the taskbar here's the screenshots
![image](https://user-images.githubusercontent.com/36896116/101191786-028aeb00-360f-11eb-98fb-ac660aefe648.png)
![image](https://user-images.githubusercontent.com/36896116/101191894-23534080-360f-11eb-9b1c-31dd009e1e10.png)

**Comment by DaddyMadu** [comment]
You can also try my fork as it's more focus towards gaming and there's option to enable or disable windows defender and if enabled the icon will be shown! https://github.com/DaddyMadu/Windows10GamingFocus/

**Comment by ChrisTitusTech** [comment]
Removing all security features in script. Specifically Defender related tweaks.
