### ISSUE TITLE
Feature request: VSCodium

### ISSUE THREAD

**Issue by kris10ansn** [ChrisTitusTech/win10script#44]
Maybe replace vscode with vscodium or add a vscodium option?

Was shocked seeing how microsoft's binaries phones home almost many times a minute, and thought this might be a good addition.

Visual Studio Code is open source, but Microsoft has been a bit sneaky with the binaries which are not open source (vscodium provides binaries that actually have the open source code in them). The only drawback to vscodium that i found is that it uses open-vsx.org instead of microsofts official extensions store out of the box, but you can easily change that. This could be an alternative when installing.

**Comment by ChrisTitusTech** [comment]
Agreed, Added for next release
