### ISSUE TITLE
Edge managed by organisation

### ISSUE THREAD

**Issue by TheEpicNoobZilla** [ChrisTitusTech/win10script#45]
After using this script my edge shows that my browser is managed by organisation. How to revert this to prescript "version"?

**Comment by tobiaspanknin** [comment]
@TheEpicNoobZilla I was manage to "revert" by deleting the regsitry key HKEY_CURRENT_USER\SOFTWARE\Policies\Microsoft\Edge

Alternatively you can just keep the policy and set the values you want to differ accordingly. I.e I only wanted to reenable addressbar history search/completion but am I fine with the other settings of the policy

**Comment by dennyamarojr** [comment]
I check the win10debloat and not see any settings that could cause the message for you. The only option that are applying is the takeover of Microsoft Edge in PDF files. Other than this, nothing is related to Microsoft Edge policies. And the setting probably is related to Microsoft Edge Legacy and not Microsoft Edge Chromium

**Comment by TheEpicNoobZilla** [comment]
Thanks it worked
> @TheEpicNoobZilla I managed to "revert" by deleting the registry key HKEY_CURRENT_USER\SOFTWARE\Policies\Microsoft\Edge
> 
> Alternatively you can just keep the policy and set the values of the settings you want to differ accordingly. I.e I only wanted to reenable addressbar history search/completion but am I fine with the other settings of the policy

**Comment by TheEpicNoobZilla** [comment]
I am using 20H2 and it affected chromium based version
> I check the win10debloat and not see any settings that could cause the message for you. The only option that are applying is the takeover of Microsoft Edge in PDF files. Other than this, nothing is related to Microsoft Edge policies. And the setting probably is related to Microsoft Edge Legacy and not Microsoft Edge Chromium

**Comment by dennyamarojr** [comment]
which setting are showing managed by your organization

**Comment by TheEpicNoobZilla** [comment]
@dennyamarojr this settings:
[https://drive.google.com/file/d/1iHtuzITeFRVBx_z5g1A6iQRoslY4wohZ/view?usp=sharing](url)

**Comment by dennyamarojr** [comment]
All the settings in the picture has nothing related to this script. This script only changes the PDF takeover, in the picture I see settings that you probably manage with gpedit.msc or regedit. The win10debloat doesn't implement any setting related to the image you upload.

As describe in the script chris only implement 
Stops edge from taking over as the default .PDF viewer

Your picture show settings like 
AddressBarMicrosoftSearchInBingProviderEnabled
AutofillAddressEnabled
AutofillCreditCardEnabled
ConfigureDoNotTrack
LocalProvidersEnabled
MetricsReportingEnabled
PaymentMethodQueryEnabled
PersonalizationReportingEnabled
SearchSuggestEnabled
SendSiteInfoToImproveServices
UserFeedbackAllowed

None of the settings chris implements, you probably run another script or a regedit file and apply these settings.

If you want to look to yourself  go to win10debloat script and search for Microsoft\Edge you will see that will not find anything, this means no Edge Chromium setting implemented.

**Comment by yashptel** [comment]
> All the settings in the picture has nothing related to this script. This script only changes the PDF takeover, in the picture I see settings that you probably manage with gpedit.msc or regedit. The win10debloat doesn't implement any setting related to the image you upload.
> 
> As describe in the script chris only implement
> Stops edge from taking over as the default .PDF viewer
> 
> Your picture show settings like
> AddressBarMicrosoftSearchInBingProviderEnabled
> AutofillAddressEnabled
> AutofillCreditCardEnabled
> ConfigureDoNotTrack
> LocalProvidersEnabled
> MetricsReportingEnabled
> PaymentMethodQueryEnabled
> PersonalizationReportingEnabled
> SearchSuggestEnabled
> SendSiteInfoToImproveServices
> UserFeedbackAllowed
> 
> None of the settings chris implements, you probably run another script or a regedit file and apply these settings.
> 
> If you want to look to yourself go to win10debloat script and search for Microsoft\Edge you will see that will not find anything, this means no Edge Chromium setting implemented.

Maybe something related to it causes it. Like changing telemetry settings or something causes it. Because same thing happened to me and I could not fix it even deleting the registry folder mention. I also tried reseting edge. Also tried deleting group policy folder from system32. But nothing seemed to work. So I am now clean installing windows again. And will see how it goes.

**Comment by dennyamarojr** [comment]
The answer for the edge managed by organization is O&O Shutup 10 recommended settings. Test in a VM and looks like O&O Shutup 10 apply a few settings in regedit to edge chromium.
