### ISSUE TITLE
Cannot find drive. A drive with the name 'HKCR' does not exist.  On Edge PDF settings

### ISSUE THREAD

**Issue by FictionalCrow** [ChrisTitusTech/win10script#47]
running the script spits out a bunch of red error messages like 

![image](https://user-images.githubusercontent.com/74490605/101418070-3e8dac80-38aa-11eb-909a-a539235c756c.png)

And edge keeps coming back and opening pdf after reboots.  doing some research it seems the script never created/mounted the HKCR drive?

**Comment by DaddyMadu** [comment]
You can try my fork its already fixed there and it's focus more towards gaming specifically, and chris might read the code and fix it as well
https://github.com/DaddyMadu/Windows10GamingFocus/

**Comment by ChrisTitusTech** [comment]
Just grabbed @DaddyMadu fix for the Edge takeover and am putting it in the commit today!

**Comment by DaddyMadu** [comment]
> Just grabbed @DaddyMadu fix for the Edge takeover and am putting it in the commit today!

Awesome work chris ❤️, keep up the good work, feel free to check my additional work and give it a spin, i tried my best to mimic what paid optimizers dose on non striped builds.
