### ISSUE TITLE
Make dark mode optional?

### ISSUE THREAD

**Issue by RamonUnch** [ChrisTitusTech/win10script#49]
I want first to say that I love this script and found myself using it several times already since it came out.
However I do not like the dark theme (too dark for me), and the same applies to many peoples I know. I do reckon that the mots geeky people do love the dark mode, but I am not one of those.
Could you make this option Optional? 
Every time I lunch the script for myself or for someone else, I lose 5 minutes looking for the option in Windows setting to restore default light theme. I personally use finely customized color scheme, and most people I know use the default Light theme.
Maybe you could have an "Enable Dark-side" prompt like you do for all the applications.

**Comment by TassiloBalbo** [comment]
You can click on Dark mode or Light mode buttons under the System tweaks section

**Comment by RamonUnch** [comment]
Ok, I understand my mistake now, I was just using the 'minimal' script, Thanks for the info.
