### ISSUE TITLE
Add Bandisoft's Honeyview (image viewer)

### ISSUE THREAD

**Issue by diras2010** [ChrisTitusTech/win10script#52]
The program is lightweight, ad-free, freeware, quite useful, and has support for multiple formats

> Image formats: BMP, JPG, GIF, PNG, PSD, DDS, JXR, WebP, J2K, JP2, TGA, TIFF, PCX, PGM, PNM, PPM, BPG
Raw image formats: DNG, CR2, CRW, NEF, NRW, ORF, RW2, PEF, SR2, RAF
Animation image formats: Animated GIF, Animated WebP, Animated BPG, Animated PNG
Archive formats for direct image viewing without extraction: ZIP, RAR, 7Z, LZH, TAR, CBR, CBZ

**Comment by ChrisTitusTech** [comment]
Added for next release
