### ISSUE TITLE
Stuck on stopping Edge from being the default for PDF

### ISSUE THREAD

**Issue by frgmnt** [ChrisTitusTech/win10script#53]
I believe it is getting stuck there because I removed Edge from my computer before I ran this script.

**Comment by dennyamarojr** [comment]
Depending on which version of windows you have, you need to see if is edge chromium or the legacy one.

**Comment by ChrisTitusTech** [comment]
I will remove this tweak as it is not needed in the new edge chromium 20H2 release of windows.
