### ISSUE TITLE
Malwarebytes marks this as a PUM

### ISSUE THREAD

**Issue by Brandon1245** [ChrisTitusTech/win10script#54]
This is a Virus Malwarebytes says this is a PUM From Malwarebytes (potentially unwanted modifications (PUMs). These potentially unwanted modifications are usually found in the Windows registry or in a browsers’ settings.) As Using O%O Shutup is a Example is a Unwanted Modification Removing Powershell for Chocolatey not even RIght i wold Like to see This to be Fixed Right 

Proof of Virus
https://www.virustotal.com/gui/file/3aff4b1cc35ccca7035d43b3913be3cebef285db663cbaf0601714b9941fc31c/detection

**Comment by Wykerd** [comment]
If you don't like the modifications this script makes, you can fork the repo and remove the modifications you would rather it not make.

**Comment by TassiloBalbo** [comment]
that's a false alarm. If you don't want some features, simply fork it and modify it

**Comment by dennyamarojr** [comment]
You really are use the detection of Qihoo-360 seriously? Didn't see any malwarebytes detection in the link. And all the commands in this project are signed and none of them are dangerous or not safe to use. All the commands you're free to check in the file, and also all the commands you can check using Microsoft Docs website.

**Comment by ChrisTitusTech** [comment]
False detection in multiple AV programs I am aware but it's not something I can do anything about.
