### ISSUE TITLE
Chrome Chocolatey Install Not Working

### ISSUE THREAD

**Issue by myxxmikeyxx** [ChrisTitusTech/win10script#56]
I was not able to install google chrome from your script with Chocolatey. 
When ever I click it the power shell does nothing but when I installed the other items it said this.

Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\WINDOWS\system32> iex ((New-Object System.Net.WebClient).DownloadString('https://git.io/JJ8R4'))
Installing Chocolatey
WARNING: It's very likely you will need to close and reopen your shell
  before you can use choco.
WARNING: You can safely ignore errors related to missing log files when
  upgrading from a version of Chocolatey less than 0.9.9.
  'Batch file could not be found' is also safe to ignore.
  'The system cannot find the file specified' - also safe.
PATH environment variable does not have C:\ProgramData\chocolatey\bin in it. Adding...
WARNING: Not setting tab completion: Profile file does not exist at
'C:\Users\admin\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1'.
Enabling Dark Mode
Installing VLC Media Player
Installing Visual Studio Code
Installing Notepad++
Installing 7-Zip Compression Tool

**Comment by dennyamarojr** [comment]
I check here and I will fix the script and contact chris for update the script, thanks for the comment.

**Comment by dennyamarojr** [comment]
@myxxmikeyxx Fix the problem, check the pull request I opened and see if installing for you

**Comment by myxxmikeyxx** [comment]
I have chrome installed manually and do not have another device to test on at this time.
