### ISSUE TITLE
Why not install Brave and OOShutUp10 with Chocolatey?

### ISSUE THREAD

**Issue by DestroyerXyz** [ChrisTitusTech/win10script#57]

**Comment by RamonUnch** [comment]
I think one good reason not to use Chocolatey for OOShutUp10 is to avoid requirement of the Chocolatey install when a user just wants the essential tweeks which requires OOShutUp. Many people for which I run this script want nothing new installed, Chocolatey is good software, but using it for OOShutUp would mean that some peoples will have to uninstall it manually later.

This is my experience of course. Personally I use choco everywhere but not everyone wants it.

**Comment by DestroyerXyz** [comment]
Yeah, I understand that but why Brave?

**Comment by skydivematy** [comment]
Because, it is the better Browser in question of privacy. And, and you get rewarded in cryptocurrency $BAT by browsing the net on specific webpages.

**Comment by DestroyerXyz** [comment]
I mean why not install it with Chocolatey

**Comment by RamonUnch** [comment]
I agree for Brave, installing it with Chocolatey would make more sense, ans simplify the script.
