### ISSUE TITLE
MenuShowDelay to 0 is too short

### ISSUE THREAD

**Issue by RamonUnch** [ChrisTitusTech/win10script#60]
I am referring to the visual fx tweaks, I think that a value of 0 for MenuShowDelay is too short, because it also corresponds to the pop-down menu delay. This means that if you set to 0 there is no way you can make a diagonal movement to go in a sub-menu.

I agree that the default 400ms is too long, but my experience is that best overall timing lies between 100 and 200ms. I personally usually stick to 200ms.

So I think that the tweak should set this value at least to 100ms, this already avoid having to be navigating through sub-menus in an ultra square fashion. It can be quite annoying when using something like classic shell or other software with a lot of sub-menu.

**Comment by ChrisTitusTech** [comment]
Thanks for the feedback changing the visualfx option to Show Delay 200 on commit today
