### ISSUE TITLE
 Enable "Your Phone" app from Microsoft

### ISSUE THREAD

**Issue by andreluizmg** [ChrisTitusTech/win10script#61]
I ran the minimal script and really like the debloat. However, I like using the "Your Phone" app from Microsoft, but I now get a splash screen on that app that says it has been "blocked by my system administrator". Is there an easy way to re-enable access to this app? or a script to re-enable. Thanks

**Comment by RamonUnch** [comment]
Reading the [main ](https://christitus.com/ultimate-windows-setup-guide/)page for this script I found an answer:

Darek Przyżycki amv1981
To fix the problem with Your Phone app, you have to remove this registry entry:
[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\System]
"EnableMmx"=-

**Comment by BrantleyF** [comment]
I've deleted "EnableMmx" & "EnableCdp" from registry and rebooted and am able to access the setting "Phone" and when I start the application "Your Phone" I'm able to see that I'm connected with my account and that I can generate a QR code (which was read by my phone), but then on the phone it loops with a screen saying something like (Look on your PC, we're checking a few things on your pc before we can ask for your consent finally - roughly translated from German). After some time it informs me that I need to make sure that "sending notification" is enabled on the PC within the "Your Phone" app, but I can't access any settings within this app.

**Comment by 3371-Alpha** [comment]
This get turned off as part of the "DisableSharedExperiences". "EnableSharedExperiences" should turn it back on.

**Comment by ChrisTitusTech** [comment]
Removing these keys in the script so this won't be needed in the future.
