### ISSUE TITLE
ummm virus?

### ISSUE THREAD

**Issue by higherleveling** [ChrisTitusTech/win10script#64]
This came up after i unzipped and ran the gui..
I had just agreed to first disclaimer and then this: https://imgur.com/a/4HaaObo

i took a screenshot

IS IT SAFE??

**Comment by 3371-Alpha** [comment]
Doubtful. It detects it as one since it modified core os files in the debloating.

**Comment by higherleveling** [comment]
oh okay. thanks for the reply

**Comment by Brandonbr1** [comment]
it is not a virus it is just mcaffe it is a bad antivirus software use malware bites
