### ISSUE TITLE
Replace Irfanview with ImageGlass?

### ISSUE THREAD

**Issue by TassiloBalbo** [ChrisTitusTech/win10script#76]
Irfanview isn't free and open source, [ImageGlass](https://github.com/d2phap/ImageGlass) is, it also looks better and has dark mode. I think ImageGlass is a better choice overall.

**Comment by DestroyerXyz** [comment]
100% agree

**Comment by ChrisTitusTech** [comment]
Never heard of it... Looks awesome! Switching it for next commit!
