### ISSUE TITLE
OneDrive not recoverable after uninstall

### ISSUE THREAD

**Issue by iGuile** [ChrisTitusTech/win10script#80]
Attempting to reinstall OneDrive after accidental uninstall has posed issues. The install file from Microsoft's website will not run, and attempting to run the recovery script also doesn't produce any valuable results for this specific issue. 

What can I do?

**Comment by Nakirasu** [comment]
You should be able to run OneDrive from the start menu after deleting this value from your computer registry;

>HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\OneDrive\DisableFileSyncNGSC

Powershell command:
`Remove-ItemProperty -Path HKLM:\SOFTWARE\Policies\Microsoft\Windows\OneDrive -Name DisableFileSyncNGSC`

**Comment by Brandonbr1** [comment]
run his restore script

**Comment by ChrisTitusTech** [comment]
Adding this in the new script update
