### ISSUE TITLE
WiFi no longer working

### ISSUE THREAD

**Issue by AstroHarry** [ChrisTitusTech/win10script#85]
Laptop can no longer find networks. It will connect to the internet through Ethernet, but not wifi. 

I tried updating wifi drivers and have spent hours on this godawful laptop locating this issue. I’m not a tech guy which is why I was dumb enough to not have a backup before doing this, but I also am not sure what 99% of what I’m doing means, so I’m sorry if it’s confusing. I’m following any website I can with similar issues. It seems my issue with with my WLAN autoconfig service. It isn’t running and it won’t let me start it due to error 1068 and it’s dependencies are running. Two dependencies are gone and one just won’t run. 

WLAN dependencies:

-Native WiFi Filter (not there)

-NDIS Usermode I/O Protocol (not there)

-Remote Procedure Call (RPC) ✅ 

-Wcmsvc (won’t run—“Windows could not start the Wcmsvc service on Local Computer. error 193:0xc1”)

Wcmsvc Dependencies:

-Network Store Interface Service ✅ 

-Remote Procedure Call (RPC) ✅ 

currently still working on finding a solution to these issues, but it’s been hours and haven’t had any luck.

**Comment by mikhoul** [comment]
Follow the advices here to reinstall the missing services to their default states:   http://batcmd.com/windows/10/services/


Regards :octocat:

**Comment by AstroHarry** [comment]
I downloaded them, following the website’s instructions, and I now find their .sys files, but the problem is persisting. I can’t find a service download for wcmsvc and it’s still not running. 

The only other thing I’ve found is that windows won’t install all updates, so I’m thinking maybe that’s the issue? When I try it either says “we could not complete install because an update server was shutting down” or it says the drivers I already have installed may be better than what they’re trying to install. I’ve followed a few articles recommendations for fixing this (running troubleshooter which said no issues detected, resetting windows update components (which I couldn’t get to work because the file directory did exist), cleared the windows update cache).

**Comment by AstroHarry** [comment]
Something that may be noteworthy is the laptop is running Windows 10 version 2004 and the update is for Windows 10 version 20H2. I saw “they share a common core operating system with an identical set of files” but I’m not sure if that means their updates can interchangeable at times.

**Comment by mikhoul** [comment]
- http://batcmd.com/windows/10/services/wcmsvc/
- https://www.tenforums.com/tutorials/57567-restore-default-services-windows-10-a.html

**Comment by Carterpersall** [comment]
If this issue is resolved, please close to prevent too much clutter in the open issues

**Comment by AstroHarry** [comment]
Not sure exactly what fixed the issue. I followed the instructions of those who commented and sort of just kept trying to update the laptop, restarting the laptop, and repeating. After about 7 cycles of updating and restarting it finally updated all the way and the wifi was fixed.
