### ISSUE TITLE
Trying to run on VirtualBox Win10 Pro guest install

### ISSUE THREAD

**Issue by mfrazzz** [ChrisTitusTech/win10script#95]
I'm trying to use this for a Win10 Pro install as a guest OS running under VirtualBox.  When I click to install Notepad++ or 7-Zip, I can see the Install line in the PS window, and I get the Operation Completed dialog box, but nothing is installed or shows up in the start menu list of applications.  It did install Choclatey and Brave, but nothing else seems to work.  I did the Low Security and Security Updates Only, but have no idea if this really did anything since the installs aren't working.  Is this an issue because I'm under VB?

Edition	Windows 10 Pro
Version	20H2
Installed on	‎3/‎10/‎2021
OS build	19042.867
Experience	Windows Feature Experience Pack 120.2212.551.0

**Comment by ChrisTitusTech** [comment]
Switching everything to Winget that will clear this up.
