### ISSUE TITLE
Breaks updates

### ISSUE THREAD

**Issue by pexeixv** [ChrisTitusTech/win10script#96]
I liked this script and used it on most of the machines that came to me until I realized that the script was breaking updates. Updating from 2004 to 20H2 was just not possible on my personal machine. I had to clean install 2004, only then was able to upgrade successfully to 20H2.

**Comment by masninja** [comment]
@pexeixv If you have selected security updates only this will happen due the configuration design to only install security updates. If I'm remember chris adds a function to restore to default settings and them you can install feature updates again.

**Comment by pexeixv** [comment]
I'm not a fan of disabling updates so I don't think I must've used the option you're talking about. Can you think of anything else that might be breaking updates?

**Comment by masninja** [comment]
@pexeixv Did you block anything in Windows Firewall? Also check if the services is running properly?

**Comment by pexeixv** [comment]
Nope. Never messed with the firewall.

**Comment by ChrisTitusTech** [comment]
There is the default settings button for update and that is the only time the script will interface with windows update. It is done with a Group Policy Object and AT NO TIME will it mess with the services or inner workings of Windows Update.

**Comment by cornelha** [comment]
I believe this has been closed prematurely, the script does in fact do something that breaks updating from 20H2 to 21H1. It would appear that some changes to telemetry settings via Group Policy could have caused this. I am currently downloading the update manually since no amount of checking for updates shows any updates after 20H2 with security updates.

**Comment by ChrisTitusTech** [comment]
20H2 and 21H1 has some really funky things going on... I'm still investigating what they did here. It's not just updates, but how it interfaces with winget and other apps as well.
